WebTask.Web/Controllers/ItemsController.cs
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebTask.Core.ViewModels;
using WebTask.Receivers.Receivers;
using WebTask.Receivers.Receivers.Implementation;

namespace WebTask.Web.Controllers
{
    public class ItemsController : Controller
    {
        public IItemReceiver ItemReceiver = new ItemReceiver();

        public async Task<ActionResult> Index()
        {
            var itemList = await this.ItemReceiver.GetList();

            return View(itemList.ToList());
        }

        public async Task<ActionResult> Edit(int id)
        {
            var details = await this.ItemReceiver.GetDetails(id);

            return View(details);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(ItemViewModel model)
        {
            await this.ItemReceiver.Update(model);

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> View(int id)
        {
            var details = await this.ItemReceiver.GetDetails(id);

            return View(details);
        }

        public async Task<ActionResult> Delete(int id)
        {
            await this.ItemReceiver.Delete(id);

            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(ItemViewModel model)
        {
            await this.ItemReceiver.Add(model);

            return RedirectToAction("Index");
        }
    }
}

WebTask.Web/Views/Items/Create.cshtml
@using WebTask.Core.ViewModels

@model ItemViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@Html.BeginForm()

<table>
    <tr>
        <td>Name: </td>
        <td>@Html.TextBoxFor(x => x.Name)</td>
    </tr>
</table>
<input type="submit" value="Create" />

WebTask.Web/Views/Items/Index.cshtml
@using WebTask.Core.ViewModels

@model List<ItemViewModel>


@{
    ViewBag.Title = "Index";
}

<h2>Items</h2>

<table>
    <th>
    <td></td>
    <td></td>
    <td></td>
    <td>Name</td>
    </th>


    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.ActionLink("Edit", "Edit", "Items")</td>
            <td>@Html.ActionLink("Delete", "Delete", "Items")</td>
            <td>@Html.ActionLink("View", "Edit", "Items")</td>
            <td>@item.Name</td>
        </tr>
    }

</table>

@Html.ActionLink("Create", "Create", "Items")